version: '3.8'

services:
  currency-pricing:
    image: andregustavoleao/princing-service-go:latest
    container_name: currency-pricing
    ports:
      - "8080:8080"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "order-trading-topic:1:1"
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data

  postgres:
    image: postgres:15
    container_name: postgres-core-customer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core-customer
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", pg_isready -U postgres ]
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data

  core-customer:
    image: andregustavoleao/cript-core-customer:latest
    container_name: core-customer
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9093:9093"

volumes:
  kafka-data:
  postgres-data: